name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Homebrew dependencies
        run: brew install mint

      - name: Restore Mint cache
        id: mint-cache
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/mint/
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}

      - name: Install Mint dependencies
        if: steps.mint-cache.outputs.cache-hit != 'true'
        run: mint bootstrap

      - name: Run linters
        run: |
          mint run swiftlint --quiet --strict
          mint run swiftformat --lint .
