name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run tests
        run: xcodebuild clean test -workspace ./.swiftpm/xcode/package.xcworkspace -scheme SwiftExec
